apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo01-wordpress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gk-duplo/argocd-test.git
    targetRevision: main
    path: apps/argo01
  destination:
    server: https://kubernetes.default.svc
    namespace: duploservices-argo01
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
